CLS
PRINT "chapter 1"
PRINT
PRINT "After the great war of man and dragon you find yourself fleeing into the local"
PRINT "cave system beyond the mystic wood of souls. You are armed with nothing but"
PRINT "your trusty bow, 3 arrows and your self sufficiency."
PRINT
PRINT "chapter objectives: make your way through the mistic woods to the cave system"
PRINT
PRINT "you are on the edge of the mysic woods there may be many dangerous creatures"
PRINT "through there. to the north is a wandering path slipping into the woods, to"
PRINT "the west is a vast lake that seems to go on forever, in the east is a huge"
PRINT "inscaleable mountain, and  finally, in the south is a morbid wasteland with"
PRINT "dragons roaming though the skies."




