# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "fuse-bindings-2.11.2" = {
      name = "fuse-bindings";
      packageName = "fuse-bindings";
      version = "2.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fuse-bindings/-/fuse-bindings-2.11.2.tgz";
        sha512 = "53gc5h3VDYY9QmFu4tFU9NgKfR51AgKGhl7Uj1EX63RDU5kiBo2ooDvBiuawlS/iyEprUnzjlcDny1N/VhWNnA==";
      };
    };
    "nan-2.14.2" = {
      name = "nan";
      packageName = "nan";
      version = "2.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.14.2.tgz";
        sha512 = "M2ufzIiINKCuDfBSAUr1vWQ+vuVcA9kqx8JJUsbQi6yf1uGRyb7HfpdfUr5qLXf3B/t8dPvcjhKMmlfnP47EzQ==";
      };
    };
    "node-gyp-build-3.9.0" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "3.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-3.9.0.tgz";
        sha512 = "zLcTg6P4AbcHPq465ZMFNXx7XpKKJh+7kkN699NiQWisR2uWYOWNWqRHAmbnmKiL4e9aLSlmy5U7rEMUXV59+A==";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
  };
  args = {
    name = "fuse";
    packageName = "fuse";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."fuse-bindings-2.11.2"
      sources."nan-2.14.2"
      sources."node-gyp-build-3.9.0"
      sources."xtend-4.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}