echo Building DanOS...
echo Compiling MBR...
nasm mbr.asm -ombr.bin
echo Compiling Partition 1,,,
nasm part1.asm -opart1.bin
echo Combining the first 2 sectors...
echo Mounting the image...
mkdir danos/
sudo mount -oloop part1.bin danos/
echo TODO finish
