# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "synaptic-1.1.4" = {
      name = "synaptic";
      packageName = "synaptic";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/synaptic/-/synaptic-1.1.4.tgz";
        sha512 = "JFtU98VDFI0uBTowgySo+UUEkc7rSVHaxx9D6dR5BK6u81G7uAxcp32Gi2SHciLpFbvJVd1Pfz7aqSNQO4EH9Q==";
      };
    };
  };
  args = {
    name = "learn";
    packageName = "learn";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."synaptic-1.1.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}