export const FILE = 'a3';
export const firstJSON = '{"I have no idea": "How this is happening"}';
export const FIRST_DEBUG = 'hi, just some kind of debug in between';
export const IN_THE = 'We are in the %s';
export const THE_OPTS = ['bottom', 'top'];
export const OUT_IS = 'The output is %o, the rand was %d and I are gewd';
export const SITE_URL = 'https://dandart.co.uk';
export const IS_AWESOME = ' is awesome.';
export const QS = 'meta[http-equiv="Who-is-awesome"]';
export const ATTR = 'content';
export const STATUS_CODE = 'statusCode';