// Generated by CoffeeScript 1.6.3
(function() {
  var Ball, MCtr, frcX, frcY, gravG, gravXCtr, gravYCtr;

  gravG = 0.1;

  gravXCtr = 800;

  gravYCtr = 500;

  MCtr = 1000;

  frcX = 0;

  frcY = 0;

  Math.sgn = function(val) {
    if (val > 0) {
      return 1;
    }
    if (val < 0) {
      return -1;
    }
    return 0;
  };

  Ball = (function() {
    function Ball(event) {
      var b, g, posX, posY, r;
      this.el = document.documentElement;
      if (event) {
        posY = event.clientY;
        posX = event.clientX;
      } else {
        posY = Math.floor(Math.random() * this.el.clientHeight);
        posX = Math.floor(Math.random() * this.el.clientWidth);
      }
      this.m = 1;
      this.gravX = 0;
      this.gravY = 0;
      this._velx = 0;
      this._vely = 0;
      this._restX = 0;
      this._restY = 0;
      this.d = document.createElement('div');
      this.d.style.borderRadius = '20px';
      this.d.style.height = '40px';
      this.d.style.width = '40px';
      this.d.style.position = 'absolute';
      r = parseInt(Math.random() * 255);
      g = parseInt(Math.random() * 255);
      b = parseInt(Math.random() * 255);
      this.d.style.backgroundColor = 'rgb(' + r + ',' + g + ',' + b + ')';
      this.d.style.top = posY - 20 + 'px';
      this.d.style.left = posX - 20 + 'px';
      document.documentElement.appendChild(this.d);
    }

    Ball.prototype.velocityX = function() {
      return this._velx;
    };

    Ball.prototype.velocityY = function() {
      return this._vely;
    };

    Ball.prototype.frame = function() {
      this.gravX = gravG * MCtr * this.m / ((this.x() - gravXCtr) ^ 2);
      this.gravY = gravG * MCtr * this.m / ((this.y() - gravYCtr) ^ 2);
      this._vely -= this.gravY;
      this._velx -= this.gravX;
      this.setX(Math.floor(this.x() + this._velx));
      this.setY(Math.floor(this.y() + this._vely));
      if (0 >= this.x() || this.x() >= this.el.clientWidth) {
        this._velx = -this._velx * this._restX;
      }
      if (0 >= this.y() || this.y() >= this.el.clientHeight) {
        return this._vely = -this._vely * this._restY;
      }
    };

    Ball.prototype.x = function() {
      return parseInt(this.d.style.left);
    };

    Ball.prototype.y = function() {
      return parseInt(this.d.style.top);
    };

    Ball.prototype.setX = function(x) {
      return this.d.style.left = x + 'px';
    };

    Ball.prototype.setY = function(y) {
      return this.d.style.top = y + 'px';
    };

    return Ball;

  })();

  $(document).ready(function() {
    var animate, balls;
    balls = [];
    $(document.documentElement).click(function(e) {
      var b;
      b = new Ball(e);
      return balls.push(b);
    });
    animate = function() {
      balls.forEach(function(ball) {
        return ball.frame();
      });
      return window.requestAnimationFrame(animate);
    };
    return animate();
  });

}).call(this);
